DROP SCHEMA IF EXISTS com_sample_final;
CREATE SCHEMA com_sample_final;

DROP TABLE IF EXISTS com_sample_final.Reise;
CREATE TABLE com_sample_final.Reise
(
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    SCHIFFNAME character varying(60) ,
    REISENR character varying(10) ,
    SEGMENT character varying(20) ,
    REISEZIEL character varying(100) ,
    REISE_VON integer,
    REISE_BIS integer,
    F_LEITER character varying(60) ,
    REISEART character varying(4) ,
    JAHR integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,filename)
);

DROP TABLE IF EXISTS com_sample_final.StatFi;
CREATE TABLE com_sample_final.StatFi
(
    STATID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NATION character varying(6) ,
    GEBIET character varying(40) ,
    OEKOREGION character varying(2) ,
    OEKO_ZONE character varying(40) ,
    TIEFENREG integer,
    TRANSECTNR integer,
    STATIONTYP character varying(10) ,
    HOLTYP character varying(8) ,
    AREA character varying(8) ,
    SUBAREA character varying(8) ,
    DIVISION character varying(8) ,
    SUBDIV character varying(8) ,
    RECTANGLE character varying(8) ,
    FLATFISH character varying(6) ,
    HERINGSREC character varying(10) ,
    BOX character varying(10) ,
    ROUNDFISH character varying(4) ,
    REGION integer,
    SUBREGION integer,
    FRIESGEB character varying(10) ,
    NSTF_AREA character varying(4) ,
    NOCHNREC character varying(10) ,
    STRATUMNR character varying(8) ,
    ZEITMERID character varying(6) ,
    NOTIZ character varying(90) ,
    NETZZAHL integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,filename) REFERENCES com_sample_final.Reise
);

DROP TABLE IF EXISTS com_sample_final.NetzFi;
CREATE TABLE com_sample_final.NetzFi
(
    NETZID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    HOLNUMMER integer,
    DATUM character varying(16) ,
    DATUMHIEV character varying(16) ,
    GBFANGB character varying(14) ,
    GLFANGB character varying(16) ,
    GBHIEV character varying(14) ,
    GLHIEV character varying(16) ,
    GBSTART real,
    GLSTART real,
    GBENDE real,
    GLENDE real,
    DISTANZ double precision,
    STRECKE double precision,
    HOLART character varying(4) ,
    HOLVERL character varying(6) ,
    TIEFEMIN integer,
    TIEFEMAX integer,
    SICHTTIEFE double precision,
    FTMIN integer,
    FTMAX integer,
    MITFTIEFE double precision,
    MITTIEFE double precision,
    ZIELART character varying(100) ,
    NETZTYP character varying(20) ,
    FANGGERAET character varying(40) ,
    FGZUSATZ character varying(40) ,
    MASCHWEITE integer,
    STEERTMAWE integer,
    GRUNDTAU character varying(40) ,
    GTAULAENGE integer,
    JAGERLAENG integer,
    NETZBRSCHB double precision,
    NOHOR double precision,
    NOVERT double precision,
    NETZUMF double precision,
    KURRLLANGE integer,
    ROLLERDUR integer,
    BAUMLAENGE integer,
    KETTENVORL integer,
    FLEETANZ integer,
    HAKENANZ integer,
    KORBANZ integer,
    SZANF integer,
    SZENDE integer,
    SCHLDAUER integer,
    SCHLRICHT integer,
    SCHLGESCHW double precision,
    SCHLGGRUND double precision,
    TFVON double precision,
    TFBIS double precision,
    SFVON double precision,
    SFBIS double precision,
    OFVON double precision,
    OFBIS double precision,
    TBODEN double precision,
    SBODEN double precision,
    OBODEN double precision,
    TOBERFL double precision,
    SOBERFL double precision,
    OOBERFL double precision,
    OEINHEIT character varying(2) ,
    TLUFT double precision,
    WINDRICHT integer,
    WINDGESCHW integer,
    WINDGEEINH character varying(2) ,
    WETTER character varying(2) ,
    BEWOELKUNG character varying(2) ,
    SEEGANG character varying(2) ,
    BODEN integer,
    GRUND integer,
    STROMS real,
    STROMK real,
    TIDE real,
    EISVER character varying(2) ,
    LICHT character varying(2) ,
    FILVOL integer,
    FLOWIN integer,
    FLOWOUT integer,
    GESFANG double precision,
    BEIFANG double precision,
    INVERTE double precision,
    ANZARTEN integer,
    NOTIZ character varying(240) ,
    VALIDITY character varying(2) ,
    BEARBSTATU character varying(12) ,
    STRATEGIE character varying(4) ,
    FI_AKT character varying(2) ,
    HY_AKT character varying(2) ,
    CH_AKT character varying(2) ,
    NS_AKT character varying(2) ,
    BE_AKT character varying(2) ,
    PL_AKT character varying(2) ,
    DI_AKT character varying(2) ,
    ANDERE_AKT character varying(40) ,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,filename) REFERENCES com_sample_final.StatFi
);

DROP TABLE IF EXISTS com_sample_final.FishFi;
CREATE TABLE com_sample_final.FishFi
(
    FISHID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    TAXCODE character varying(40) ,
    FARTNAME character varying(100) ,
    STOCK_ID character varying(50) ,
    GESAMTKG double precision,
    GESAMTSTCK double precision,
    MITTGEW double precision,
    UPKG double precision,
    UPSTCK double precision,
    GEMESSENE integer,
    PROBEKG_F double precision,
    PROBEST_F double precision,
    PROBEKG_M double precision,
    PROBEST_M double precision,
    PROBEKG_U double precision,
    PROBEST_U double precision,
    STATUS character varying(24) ,
    KOM_STATUS character varying(12) ,
    DATENQCODE character varying(4) ,
    MLAENG character varying(40) ,
    UNMLAENG character varying(40) ,
    MINLAENG double precision,
    MAXLAENG double precision,
    INCLAENG double precision,
    MEANLAENG double precision,
    MEANWEIGHT double precision,
    ANZSINGLE integer,
    NOTIZ character varying(90) ,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,filename) REFERENCES com_sample_final.NetzFi
);

DROP TABLE IF EXISTS com_sample_final.MrktFi;
CREATE TABLE com_sample_final.MrktFi
(
    MRKTID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    TAXCODE character varying(40) ,
    FARTNAME character varying(100) ,
    STOCK_ID character varying(50) ,
    GESAMTKG double precision,
    GESAMTSTCK double precision,
    MITTGEW double precision,
    UPKG double precision,
    UPSTCK double precision,
    GEMESSENE integer,
    PROBEKG_F double precision,
    PROBEST_F double precision,
    PROBEKG_M double precision,
    PROBEST_M double precision,
    PROBEKG_U double precision,
    PROBEST_U double precision,
    STATUS character varying(24) ,
    KOM_STATUS character varying(12) ,
    DATENQCODE character varying(4) ,
    MLAENG character varying(40) ,
    UNMLAENG character varying(40) ,
    MINLAENG double precision,
    MAXLAENG double precision,
    INCLAENG double precision,
    MEANLAENG double precision,
    MEANWEIGHT double precision,
    ANZSINGLE integer,
    NOTIZ character varying(90) ,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,filename) REFERENCES com_sample_final.NetzFi
);

DROP TABLE IF EXISTS com_sample_final.DiscFi;
CREATE TABLE com_sample_final.DiscFi
(
    DISCID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    TAXCODE character varying(40) ,
    FARTNAME character varying(100) ,
    STOCK_ID character varying(50) ,
    GESAMTKG double precision,
    GESAMTSTCK double precision,
    MITTGEW double precision,
    UPKG double precision,
    UPSTCK double precision,
    GEMESSENE integer,
    PROBEKG_F double precision,
    PROBEST_F double precision,
    PROBEKG_M double precision,
    PROBEST_M double precision,
    PROBEKG_U double precision,
    PROBEST_U double precision,
    STATUS character varying(24) ,
    KOM_STATUS character varying(12) ,
    DATENQCODE character varying(4) ,
    MLAENG character varying(40) ,
    UNMLAENG character varying(40) ,
    MINLAENG double precision,
    MAXLAENG double precision,
    INCLAENG double precision,
    MEANLAENG double precision,
    MEANWEIGHT double precision,
    ANZSINGLE integer,
    NOTIZ character varying(90) ,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,filename) REFERENCES com_sample_final.NetzFi
);

DROP TABLE IF EXISTS com_sample_final.LengFi;
CREATE TABLE com_sample_final.LengFi
(
    LENGID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    SEX character varying(2) ,
    STADIUM character varying(10) ,
    LAENGE double precision,
    LANZAHL real,
    HANZAHL double precision,
    GEWICHT double precision,
    GANZAHL integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,LAENGE,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename) REFERENCES com_sample_final.FishFi
);

DROP TABLE IF EXISTS com_sample_final.MLenFi;
CREATE TABLE com_sample_final.MLenFi
(
    MLENID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    SEX character varying(2) ,
    STADIUM character varying(10) ,
    LAENGE double precision,
    HANZAHL double precision,
    LANZAHL real,
    GEWICHT double precision,
    GANZAHL integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,LAENGE,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename) REFERENCES com_sample_final.MrktFi
);

DROP TABLE IF EXISTS com_sample_final.DLenFi;
CREATE TABLE com_sample_final.DLenFi
(
    DLENID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    SEX character varying(2) ,
    STADIUM character varying(10) ,
    LAENGE double precision,
    HANZAHL double precision,
    LANZAHL real,
    GEWICHT double precision,
    GANZAHL integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,LAENGE,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename) REFERENCES com_sample_final.DiscFi
);

DROP TABLE IF EXISTS com_sample_final.SnglIOR;
CREATE TABLE com_sample_final.SnglIOR
(
    SNGLID integer,
    SCHIFF character varying(8) ,
    EU_NR character varying(26) ,
    REISENR character varying(10) ,
    JAHR integer,
    QUARTAL integer,
    MONAT smallint,
    STATION integer,
    STATDATUM character varying(16) ,
    NETZ integer,
    FISH integer,
    ARTCODE character varying(24) ,
    FANGART character varying(2) ,
    IDENTNR integer,
    ALTER integer,
    ALTERZUS character varying(6) ,
    AUSSENZONE character varying(2) ,
    LESBARKEIT character varying(2) ,
    WINTERRING integer,
    JAHRGANG integer,
    OTOTYPE character varying(2) ,
    LAICHZEIT character varying(2) ,
    LAENGE double precision,
    TOTALGEW double precision,
    SLGEW double precision,
    SEX character varying(2) ,
    REIFE character varying(10) ,
    REIFEZUS character varying(6) ,
    MILAICHMON integer,
    WIRBELANZ integer,
    TAXONANZ integer,
    PARAINDEX character varying(2) ,
    PARAANZ integer,
    EINGEWFETT character varying(2) ,
    DOR1FLOANZ integer,
    DOR2FLOANZ integer,
    PECTFLOANZ integer,
    KIEMENRF integer,
    MAGFULLGR character varying(2) ,
    NAHRUNG1 character varying(4) ,
    NAHRUNG2 character varying(4) ,
    NAHRUNG3 character varying(4) ,
    LYMPHOCYS character varying(2) ,
    LFLUNDER character varying(2) ,
    MOPSKOPF character varying(2) ,
    WIRBELDEFO character varying(2) ,
    MELANOCYT character varying(2) ,
    HAUTVERL character varying(2) ,
    GESCHWUERE character varying(2) ,
    TUMORE character varying(2) ,
    LEBERFARBE character varying(2) ,
    GONADENGEW double precision,
    LEBERGEW double precision,
    KIELSCHUPP integer,
    AUGDMESS integer,
    SCHULTEH integer,
    filename character varying(50),
    PRIMARY KEY(JAHR,EU_NR,REISENR,STATION,NETZ,FISH,filename),
    FOREIGN KEY(JAHR,EU_NR,REISENR,STATION,NETZ,filename) REFERENCES com_sample_final.NetzFi
);
