# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_gear.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_gear(object):
    def setupUi(self, frm_gear):
        frm_gear.setObjectName("frm_gear")
        frm_gear.resize(576, 614)
        self.verticalLayout = QtWidgets.QVBoxLayout(frm_gear)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_netz = QtWidgets.QComboBox(frm_gear)
        self.cb_netz.setMinimumSize(QtCore.QSize(284, 20))
        self.cb_netz.setObjectName("cb_netz")
        self.gridLayout_2.addWidget(self.cb_netz, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 2, 1)
        self.label = QtWidgets.QLabel(frm_gear)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.edit_minDepth = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_minDepth.sizePolicy().hasHeightForWidth())
        self.edit_minDepth.setSizePolicy(sizePolicy)
        self.edit_minDepth.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_minDepth.setObjectName("edit_minDepth")
        self.gridLayout.addWidget(self.edit_minDepth, 1, 0, 1, 1)
        self.edit_maxDepth = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_maxDepth.sizePolicy().hasHeightForWidth())
        self.edit_maxDepth.setSizePolicy(sizePolicy)
        self.edit_maxDepth.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_maxDepth.setObjectName("edit_maxDepth")
        self.gridLayout.addWidget(self.edit_maxDepth, 1, 1, 1, 1)
        self.edit_waterDepth = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_waterDepth.sizePolicy().hasHeightForWidth())
        self.edit_waterDepth.setSizePolicy(sizePolicy)
        self.edit_waterDepth.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_waterDepth.setObjectName("edit_waterDepth")
        self.gridLayout.addWidget(self.edit_waterDepth, 1, 2, 1, 1)
        self.edit_nation = QtWidgets.QLineEdit(frm_gear)
        self.edit_nation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_nation.sizePolicy().hasHeightForWidth())
        self.edit_nation.setSizePolicy(sizePolicy)
        self.edit_nation.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_nation.setObjectName("edit_nation")
        self.gridLayout.addWidget(self.edit_nation, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1)
        self.edit_tier5 = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tier5.sizePolicy().hasHeightForWidth())
        self.edit_tier5.setSizePolicy(sizePolicy)
        self.edit_tier5.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_tier5.setObjectName("edit_tier5")
        self.gridLayout.addWidget(self.edit_tier5, 3, 0, 1, 1)
        self.edit_tier6 = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_tier6.sizePolicy().hasHeightForWidth())
        self.edit_tier6.setSizePolicy(sizePolicy)
        self.edit_tier6.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_tier6.setObjectName("edit_tier6")
        self.gridLayout.addWidget(self.edit_tier6, 3, 1, 1, 1)
        self.edit_gear = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_gear.sizePolicy().hasHeightForWidth())
        self.edit_gear.setSizePolicy(sizePolicy)
        self.edit_gear.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_gear.setObjectName("edit_gear")
        self.gridLayout.addWidget(self.edit_gear, 3, 2, 1, 1)
        self.edit_meshSizeRange = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_meshSizeRange.sizePolicy().hasHeightForWidth())
        self.edit_meshSizeRange.setSizePolicy(sizePolicy)
        self.edit_meshSizeRange.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_meshSizeRange.setObjectName("edit_meshSizeRange")
        self.gridLayout.addWidget(self.edit_meshSizeRange, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 1, 1, 1)
        self.edit_device = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_device.sizePolicy().hasHeightForWidth())
        self.edit_device.setSizePolicy(sizePolicy)
        self.edit_device.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_device.setObjectName("edit_device")
        self.gridLayout.addWidget(self.edit_device, 5, 0, 1, 1)
        self.edit_deviceMesh = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_deviceMesh.sizePolicy().hasHeightForWidth())
        self.edit_deviceMesh.setSizePolicy(sizePolicy)
        self.edit_deviceMesh.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_deviceMesh.setObjectName("edit_deviceMesh")
        self.gridLayout.addWidget(self.edit_deviceMesh, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 3, 1, 1)
        self.edit_spGroup = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_spGroup.sizePolicy().hasHeightForWidth())
        self.edit_spGroup.setSizePolicy(sizePolicy)
        self.edit_spGroup.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_spGroup.setObjectName("edit_spGroup")
        self.gridLayout.addWidget(self.edit_spGroup, 7, 0, 1, 1)
        self.edit_sp = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_sp.sizePolicy().hasHeightForWidth())
        self.edit_sp.setSizePolicy(sizePolicy)
        self.edit_sp.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_sp.setObjectName("edit_sp")
        self.gridLayout.addWidget(self.edit_sp, 7, 1, 1, 1)
        self.edit_spNum = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_spNum.sizePolicy().hasHeightForWidth())
        self.edit_spNum.setSizePolicy(sizePolicy)
        self.edit_spNum.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_spNum.setObjectName("edit_spNum")
        self.gridLayout.addWidget(self.edit_spNum, 7, 2, 1, 1)
        self.edit_catch = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_catch.sizePolicy().hasHeightForWidth())
        self.edit_catch.setSizePolicy(sizePolicy)
        self.edit_catch.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_catch.setObjectName("edit_catch")
        self.gridLayout.addWidget(self.edit_catch, 7, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 2, 1, 1)
        self.edit_gearAdd = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_gearAdd.sizePolicy().hasHeightForWidth())
        self.edit_gearAdd.setSizePolicy(sizePolicy)
        self.edit_gearAdd.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_gearAdd.setObjectName("edit_gearAdd")
        self.gridLayout.addWidget(self.edit_gearAdd, 9, 0, 1, 1)
        self.edit_meshSize = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_meshSize.sizePolicy().hasHeightForWidth())
        self.edit_meshSize.setSizePolicy(sizePolicy)
        self.edit_meshSize.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_meshSize.setObjectName("edit_meshSize")
        self.gridLayout.addWidget(self.edit_meshSize, 9, 1, 1, 1)
        self.edit_codendMeshSize = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_codendMeshSize.sizePolicy().hasHeightForWidth())
        self.edit_codendMeshSize.setSizePolicy(sizePolicy)
        self.edit_codendMeshSize.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_codendMeshSize.setObjectName("edit_codendMeshSize")
        self.gridLayout.addWidget(self.edit_codendMeshSize, 9, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 10, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 10, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 10, 3, 1, 1)
        self.edit_footrope = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_footrope.sizePolicy().hasHeightForWidth())
        self.edit_footrope.setSizePolicy(sizePolicy)
        self.edit_footrope.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_footrope.setObjectName("edit_footrope")
        self.gridLayout.addWidget(self.edit_footrope, 11, 0, 1, 1)
        self.edit_footropeLength = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_footropeLength.sizePolicy().hasHeightForWidth())
        self.edit_footropeLength.setSizePolicy(sizePolicy)
        self.edit_footropeLength.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_footropeLength.setObjectName("edit_footropeLength")
        self.gridLayout.addWidget(self.edit_footropeLength, 11, 1, 1, 1)
        self.edit_jagerLength = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_jagerLength.sizePolicy().hasHeightForWidth())
        self.edit_jagerLength.setSizePolicy(sizePolicy)
        self.edit_jagerLength.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_jagerLength.setObjectName("edit_jagerLength")
        self.gridLayout.addWidget(self.edit_jagerLength, 11, 2, 1, 1)
        self.edit_netBoard = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_netBoard.sizePolicy().hasHeightForWidth())
        self.edit_netBoard.setSizePolicy(sizePolicy)
        self.edit_netBoard.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_netBoard.setObjectName("edit_netBoard")
        self.gridLayout.addWidget(self.edit_netBoard, 11, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 12, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 12, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 12, 2, 1, 1)
        self.edit_netHori = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_netHori.sizePolicy().hasHeightForWidth())
        self.edit_netHori.setSizePolicy(sizePolicy)
        self.edit_netHori.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_netHori.setObjectName("edit_netHori")
        self.gridLayout.addWidget(self.edit_netHori, 13, 0, 1, 1)
        self.edit_netVert = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_netVert.sizePolicy().hasHeightForWidth())
        self.edit_netVert.setSizePolicy(sizePolicy)
        self.edit_netVert.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_netVert.setObjectName("edit_netVert")
        self.gridLayout.addWidget(self.edit_netVert, 13, 1, 1, 1)
        self.edit_netGirth = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_netGirth.sizePolicy().hasHeightForWidth())
        self.edit_netGirth.setSizePolicy(sizePolicy)
        self.edit_netGirth.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_netGirth.setObjectName("edit_netGirth")
        self.gridLayout.addWidget(self.edit_netGirth, 13, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 14, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 14, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 14, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 14, 3, 1, 1)
        self.edit_curlLineLength = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_curlLineLength.sizePolicy().hasHeightForWidth())
        self.edit_curlLineLength.setSizePolicy(sizePolicy)
        self.edit_curlLineLength.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_curlLineLength.setObjectName("edit_curlLineLength")
        self.gridLayout.addWidget(self.edit_curlLineLength, 15, 0, 1, 1)
        self.edit_rollerDiam = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_rollerDiam.sizePolicy().hasHeightForWidth())
        self.edit_rollerDiam.setSizePolicy(sizePolicy)
        self.edit_rollerDiam.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_rollerDiam.setObjectName("edit_rollerDiam")
        self.gridLayout.addWidget(self.edit_rollerDiam, 15, 1, 1, 1)
        self.edit_beamLength = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_beamLength.sizePolicy().hasHeightForWidth())
        self.edit_beamLength.setSizePolicy(sizePolicy)
        self.edit_beamLength.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_beamLength.setObjectName("edit_beamLength")
        self.gridLayout.addWidget(self.edit_beamLength, 15, 2, 1, 1)
        self.edit_beamChains = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_beamChains.sizePolicy().hasHeightForWidth())
        self.edit_beamChains.setSizePolicy(sizePolicy)
        self.edit_beamChains.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_beamChains.setObjectName("edit_beamChains")
        self.gridLayout.addWidget(self.edit_beamChains, 15, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 16, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 16, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 16, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 16, 3, 1, 1)
        self.edit_setNetNum = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_setNetNum.sizePolicy().hasHeightForWidth())
        self.edit_setNetNum.setSizePolicy(sizePolicy)
        self.edit_setNetNum.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_setNetNum.setObjectName("edit_setNetNum")
        self.gridLayout.addWidget(self.edit_setNetNum, 17, 0, 1, 1)
        self.edit_setNetLength = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_setNetLength.sizePolicy().hasHeightForWidth())
        self.edit_setNetLength.setSizePolicy(sizePolicy)
        self.edit_setNetLength.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_setNetLength.setObjectName("edit_setNetLength")
        self.gridLayout.addWidget(self.edit_setNetLength, 17, 1, 1, 1)
        self.edit_setNetHeight = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_setNetHeight.sizePolicy().hasHeightForWidth())
        self.edit_setNetHeight.setSizePolicy(sizePolicy)
        self.edit_setNetHeight.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_setNetHeight.setObjectName("edit_setNetHeight")
        self.gridLayout.addWidget(self.edit_setNetHeight, 17, 2, 1, 1)
        self.edit_setNetTotal = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_setNetTotal.sizePolicy().hasHeightForWidth())
        self.edit_setNetTotal.setSizePolicy(sizePolicy)
        self.edit_setNetTotal.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_setNetTotal.setObjectName("edit_setNetTotal")
        self.gridLayout.addWidget(self.edit_setNetTotal, 17, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 18, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 18, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 18, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 18, 3, 1, 1)
        self.edit_pinger = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pinger.sizePolicy().hasHeightForWidth())
        self.edit_pinger.setSizePolicy(sizePolicy)
        self.edit_pinger.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_pinger.setObjectName("edit_pinger")
        self.gridLayout.addWidget(self.edit_pinger, 19, 0, 1, 1)
        self.edit_pingerType = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pingerType.sizePolicy().hasHeightForWidth())
        self.edit_pingerType.setSizePolicy(sizePolicy)
        self.edit_pingerType.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_pingerType.setObjectName("edit_pingerType")
        self.gridLayout.addWidget(self.edit_pingerType, 19, 1, 1, 1)
        self.edit_hooks = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_hooks.sizePolicy().hasHeightForWidth())
        self.edit_hooks.setSizePolicy(sizePolicy)
        self.edit_hooks.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_hooks.setObjectName("edit_hooks")
        self.gridLayout.addWidget(self.edit_hooks, 19, 2, 1, 1)
        self.edit_traps = QtWidgets.QLineEdit(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_traps.sizePolicy().hasHeightForWidth())
        self.edit_traps.setSizePolicy(sizePolicy)
        self.edit_traps.setMinimumSize(QtCore.QSize(130, 20))
        self.edit_traps.setObjectName("edit_traps")
        self.gridLayout.addWidget(self.edit_traps, 19, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(frm_gear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(85, 34))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_3.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(frm_gear)
        QtCore.QMetaObject.connectSlotsByName(frm_gear)

    def retranslateUi(self, frm_gear):
        _translate = QtCore.QCoreApplication.translate
        frm_gear.setWindowTitle(_translate("frm_gear", "Dialog"))
        self.label.setText(_translate("frm_gear", "Netz"))
        self.label_2.setText(_translate("frm_gear", "Minimum Fangtiefe"))
        self.label_38.setText(_translate("frm_gear", "Maximum Fangtiefe"))
        self.label_37.setText(_translate("frm_gear", "Wassertiefe"))
        self.label_4.setText(_translate("frm_gear", "Gear National"))
        self.label_5.setText(_translate("frm_gear", "Metier Level 5"))
        self.label_6.setText(_translate("frm_gear", "Metier Level 6"))
        self.label_7.setText(_translate("frm_gear", "Gear"))
        self.label_8.setText(_translate("frm_gear", "Mesh size range"))
        self.label_9.setText(_translate("frm_gear", "Selection Device"))
        self.label_10.setText(_translate("frm_gear", "Selection Device Mesh"))
        self.label_12.setText(_translate("frm_gear", "Target Species Group"))
        self.label_11.setText(_translate("frm_gear", "Target Species"))
        self.label_17.setText(_translate("frm_gear", "Number Species"))
        self.label_13.setText(_translate("frm_gear", "Total Catch"))
        self.label_19.setText(_translate("frm_gear", "Netzbeschreibung"))
        self.label_18.setText(_translate("frm_gear", "Maschenweite"))
        self.label_14.setText(_translate("frm_gear", "Steert-Maschenweite"))
        self.label_23.setText(_translate("frm_gear", "Grundtau"))
        self.label_15.setText(_translate("frm_gear", "Grundtaulänge"))
        self.label_22.setText(_translate("frm_gear", "Jagerlänge"))
        self.label_16.setText(_translate("frm_gear", "Scherbreite"))
        self.label_24.setText(_translate("frm_gear", "Netzöffnung horizontal"))
        self.label_21.setText(_translate("frm_gear", "Netzöffnung vertikal"))
        self.label_20.setText(_translate("frm_gear", "Netzumfang"))
        self.label_29.setText(_translate("frm_gear", "Kurrleinenlänge"))
        self.label_25.setText(_translate("frm_gear", "Rollerdurchmesser"))
        self.label_31.setText(_translate("frm_gear", "Baumlänge"))
        self.label_30.setText(_translate("frm_gear", "Kettenvorlauflänge"))
        self.label_26.setText(_translate("frm_gear", "Fleet Anzahl"))
        self.label_35.setText(_translate("frm_gear", "Fleet Länge"))
        self.label_27.setText(_translate("frm_gear", "Fleet Höhe"))
        self.label_34.setText(_translate("frm_gear", "Stellnetzlänge total"))
        self.label_28.setText(_translate("frm_gear", "Pinger"))
        self.label_36.setText(_translate("frm_gear", "Pingertyp"))
        self.label_33.setText(_translate("frm_gear", "Haken Anzahl"))
        self.label_32.setText(_translate("frm_gear", "Fallen Anzahl"))
        self.btn_save.setText(_translate("frm_gear", "Speichern"))
