# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_cruise.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_cruise(object):
    def setupUi(self, frm_cruise):
        frm_cruise.setObjectName("frm_cruise")
        frm_cruise.setWindowModality(QtCore.Qt.NonModal)
        frm_cruise.resize(510, 226)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_cruise.sizePolicy().hasHeightForWidth())
        frm_cruise.setSizePolicy(sizePolicy)
        frm_cruise.setMinimumSize(QtCore.QSize(510, 220))
        self.gridLayout = QtWidgets.QGridLayout(frm_cruise)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.edit_jahr = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_jahr.sizePolicy().hasHeightForWidth())
        self.edit_jahr.setSizePolicy(sizePolicy)
        self.edit_jahr.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_jahr.setFont(font)
        self.edit_jahr.setObjectName("edit_jahr")
        self.gridLayout.addWidget(self.edit_jahr, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.edit_eunum = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_eunum.sizePolicy().hasHeightForWidth())
        self.edit_eunum.setSizePolicy(sizePolicy)
        self.edit_eunum.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_eunum.setFont(font)
        self.edit_eunum.setObjectName("edit_eunum")
        self.gridLayout.addWidget(self.edit_eunum, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.edit_cruisenum = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_cruisenum.sizePolicy().hasHeightForWidth())
        self.edit_cruisenum.setSizePolicy(sizePolicy)
        self.edit_cruisenum.setMinimumSize(QtCore.QSize(110, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_cruisenum.setFont(font)
        self.edit_cruisenum.setObjectName("edit_cruisenum")
        self.gridLayout.addWidget(self.edit_cruisenum, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.edit_shipname = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_shipname.sizePolicy().hasHeightForWidth())
        self.edit_shipname.setSizePolicy(sizePolicy)
        self.edit_shipname.setMinimumSize(QtCore.QSize(130, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_shipname.setFont(font)
        self.edit_shipname.setObjectName("edit_shipname")
        self.gridLayout.addWidget(self.edit_shipname, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.edit_cruisetype = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_cruisetype.sizePolicy().hasHeightForWidth())
        self.edit_cruisetype.setSizePolicy(sizePolicy)
        self.edit_cruisetype.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_cruisetype.setFont(font)
        self.edit_cruisetype.setObjectName("edit_cruisetype")
        self.gridLayout.addWidget(self.edit_cruisetype, 2, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(42, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.edit_shipsign = QtWidgets.QLineEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_shipsign.sizePolicy().hasHeightForWidth())
        self.edit_shipsign.setSizePolicy(sizePolicy)
        self.edit_shipsign.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.edit_shipsign.setFont(font)
        self.edit_shipsign.setObjectName("edit_shipsign")
        self.gridLayout.addWidget(self.edit_shipsign, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.date_start = QtWidgets.QDateEdit(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_start.sizePolicy().hasHeightForWidth())
        self.date_start.setSizePolicy(sizePolicy)
        self.date_start.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.date_start.setFont(font)
        self.date_start.setAccessibleDescription("")
        self.date_start.setObjectName("date_start")
        self.gridLayout.addWidget(self.date_start, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 4, 1, 1)
        self.date_end = QtWidgets.QDateEdit(frm_cruise)
        self.date_end.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_end.sizePolicy().hasHeightForWidth())
        self.date_end.setSizePolicy(sizePolicy)
        self.date_end.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.date_end.setFont(font)
        self.date_end.setObjectName("date_end")
        self.gridLayout.addWidget(self.date_end, 4, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.cb_HarbourStart = QtWidgets.QComboBox(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_HarbourStart.sizePolicy().hasHeightForWidth())
        self.cb_HarbourStart.setSizePolicy(sizePolicy)
        self.cb_HarbourStart.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.cb_HarbourStart.setFont(font)
        self.cb_HarbourStart.setObjectName("cb_HarbourStart")
        self.gridLayout.addWidget(self.cb_HarbourStart, 5, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 4, 1, 1)
        self.cb_HarbourEnd = QtWidgets.QComboBox(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_HarbourEnd.sizePolicy().hasHeightForWidth())
        self.cb_HarbourEnd.setSizePolicy(sizePolicy)
        self.cb_HarbourEnd.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.cb_HarbourEnd.setFont(font)
        self.cb_HarbourEnd.setObjectName("cb_HarbourEnd")
        self.gridLayout.addWidget(self.cb_HarbourEnd, 5, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(85, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 2)
        self.cb_leader = QtWidgets.QComboBox(frm_cruise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_leader.sizePolicy().hasHeightForWidth())
        self.cb_leader.setSizePolicy(sizePolicy)
        self.cb_leader.setMinimumSize(QtCore.QSize(150, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.cb_leader.setFont(font)
        self.cb_leader.setObjectName("cb_leader")
        self.gridLayout.addWidget(self.cb_leader, 8, 0, 1, 3)

        self.retranslateUi(frm_cruise)
        QtCore.QMetaObject.connectSlotsByName(frm_cruise)

    def retranslateUi(self, frm_cruise):
        _translate = QtCore.QCoreApplication.translate
        frm_cruise.setWindowTitle(_translate("frm_cruise", "Form"))
        self.label.setText(_translate("frm_cruise", "Jahr"))
        self.label_4.setText(_translate("frm_cruise", "EU Nummer"))
        self.label_2.setText(_translate("frm_cruise", "Reisenummer"))
        self.label_5.setText(_translate("frm_cruise", "Schiffname"))
        self.label_3.setText(_translate("frm_cruise", "Reisetype"))
        self.label_6.setText(_translate("frm_cruise", "Schiffsign"))
        self.label_7.setText(_translate("frm_cruise", "Start Datum"))
        self.label_8.setText(_translate("frm_cruise", "End Datum"))
        self.label_9.setText(_translate("frm_cruise", "Start Hafen"))
        self.label_10.setText(_translate("frm_cruise", "End Hafen"))
        self.label_11.setText(_translate("frm_cruise", "Beprober"))
