# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_enviro.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_weather(object):
    def setupUi(self, frm_weather):
        frm_weather.setObjectName("frm_weather")
        frm_weather.resize(571, 115)
        self.gridLayout = QtWidgets.QGridLayout(frm_weather)
        self.gridLayout.setObjectName("gridLayout")
        self.sb_weather = QtWidgets.QSpinBox(frm_weather)
        self.sb_weather.setMaximum(9999)
        self.sb_weather.setObjectName("sb_weather")
        self.gridLayout.addWidget(self.sb_weather, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.sb_currents = QtWidgets.QSpinBox(frm_weather)
        self.sb_currents.setMaximum(9999)
        self.sb_currents.setObjectName("sb_currents")
        self.gridLayout.addWidget(self.sb_currents, 4, 3, 1, 1)
        self.sb_wind_dir = QtWidgets.QSpinBox(frm_weather)
        self.sb_wind_dir.setMaximum(9999)
        self.sb_wind_dir.setObjectName("sb_wind_dir")
        self.gridLayout.addWidget(self.sb_wind_dir, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.sb_temp_water = QtWidgets.QDoubleSpinBox(frm_weather)
        self.sb_temp_water.setObjectName("sb_temp_water")
        self.gridLayout.addWidget(self.sb_temp_water, 4, 0, 1, 1)
        self.sb_light = QtWidgets.QSpinBox(frm_weather)
        self.sb_light.setMaximum(9999)
        self.sb_light.setObjectName("sb_light")
        self.gridLayout.addWidget(self.sb_light, 4, 2, 1, 1)
        self.sb_wind_speed = QtWidgets.QSpinBox(frm_weather)
        self.sb_wind_speed.setMaximum(9999)
        self.sb_wind_speed.setObjectName("sb_wind_speed")
        self.gridLayout.addWidget(self.sb_wind_speed, 1, 0, 1, 1)
        self.sb_cloud = QtWidgets.QSpinBox(frm_weather)
        self.sb_cloud.setMaximum(9999)
        self.sb_cloud.setObjectName("sb_cloud")
        self.gridLayout.addWidget(self.sb_cloud, 1, 2, 1, 1)
        self.sb_temp_air = QtWidgets.QDoubleSpinBox(frm_weather)
        self.sb_temp_air.setObjectName("sb_temp_air")
        self.gridLayout.addWidget(self.sb_temp_air, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(frm_weather)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(frm_weather)
        QtCore.QMetaObject.connectSlotsByName(frm_weather)

    def retranslateUi(self, frm_weather):
        _translate = QtCore.QCoreApplication.translate
        frm_weather.setWindowTitle(_translate("frm_weather", "Form"))
        self.label_8.setText(_translate("frm_weather", "Strömungen"))
        self.label_4.setText(_translate("frm_weather", "Lufttemperatur"))
        self.label_6.setText(_translate("frm_weather", "Wetter"))
        self.label_3.setText(_translate("frm_weather", "Bewölkung"))
        self.label_2.setText(_translate("frm_weather", "Windrichtung"))
        self.label_7.setText(_translate("frm_weather", "Lichtverhältnisse"))
        self.label_5.setText(_translate("frm_weather", "Wassertemperatur"))
        self.label.setText(_translate("frm_weather", "Windgeschwindigkeit"))
